#!/bin/sh

# Suppress kernel messages
dmesg -n 1
clear

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs udev /dev 


# Setup networking
for NETDEV in /sys/class/net/* ; do
  ip link set ${NETDEV##*/} up
  [ ${NETDEV##*/} != lo ] && udhcpc -b -i ${NETDEV##*/} -s /etc/network.sh
done
#ip link set eth0 up
#[ eth0 != lo ] && udhcpc -b -i eth0 -s /etc/network.sh
clear

exec /sbin/init

